Executable = comp.sh
X = $(Process) + 1
Arguments = 1
Log = $INT(X,%d).log
Output = $INT(X,%d).out
Error = $INT(X,%d).err
should_transfer_files = YES
transfer_input_files = ../source
when_to_transfer_output = ON_EXIT
initialdir = Run$INT(X,%d)
transfer_output_files = SGpp_build/AvaPEle.tsv, SGpp_build/ElePPhot.tsv, SGpp_build/AvaTot.tsv, SGpp_build/EleEner.tsv, SGpp_build/ElePos.tsv, SGpp_build/EEnerPos.tsv
RequestDisk = 500M
RequestMemory = 1G
Queue 100